name: Deploy Site

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to github pages with gh-pages
      uses: ShanuDey/deploy-react-to-ghpages@v1.0
